export { default as CategoryPage } from './CategoryPage'
export { default as NotFoundPage } from './NotFound'
export { default as ProductDetailPage } from './ProductDetailPage'
export { default as ShopPage } from './ShopPage'
export { default as ContactPage } from './ContactPage'
